apiVersion: 1

datasources:
  - name: LAN Map History
    uid: lan-map-sqlite
    type: frser-sqlite-datasource
    access: proxy
    isDefault: false
    editable: false
    jsonData:
      path: /var/lib/grafana/lan-map/history.db
